[custom0]
binding='<Super>t'
command='kitty'
name='Start Terminal'

[custom1]
binding='<Super>b'
command='vivaldi.vivaldi-stable'
name='Vivaldi'

[custom2]
binding='<Super>e'
command='nautilus'
name='Files Explorer'
