[/]
app-picker-layout=[{'org.gnome.clocks.desktop': <{'position': <0>}>, 'org.gnome.Totem.desktop': <{'position': <1>}>, 'org.gnome.Calculator.desktop': <{'position': <2>}>, '1password.desktop': <{'position': <3>}>, 'software-properties-drivers.desktop': <{'position': <4>}>, 'simple-scan.desktop': <{'position': <5>}>, 'android-studio_android-studio.desktop': <{'position': <6>}>, 'org.gnome.Settings.desktop': <{'position': <7>}>, 'snap-store_snap-store.desktop': <{'position': <8>}>, 'org.gnome.SystemMonitor.desktop': <{'position': <9>}>, 'btop.desktop': <{'position': <10>}>, 'caffeine.desktop': <{'position': <11>}>, 'org.gnome.Terminal.desktop': <{'position': <12>}>, 'caffeine-indicator.desktop': <{'position': <13>}>, 'Utilities': <{'position': <14>}>, 'org.gnome.Calendar.desktop': <{'position': <15>}>, 'org.gnome.Snapshot.desktop': <{'position': <16>}>, 'yelp.desktop': <{'position': <17>}>, 'cheese_cheese.desktop': <{'position': <18>}>, 'chromium_chromium.desktop': <{'position': <19>}>, 'com.mattjakeman.ExtensionManager.desktop': <{'position': <20>}>, 'org.gnome.Nautilus.desktop': <{'position': <21>}>, 'firefox_firefox.desktop': <{'position': <22>}>, 'firmware-updater_firmware-updater.desktop': <{'position': <23>}>}, {'grub-customizer.desktop': <{'position': <0>}>, 'htop.desktop': <{'position': <1>}>, 'org.gnome.eog.desktop': <{'position': <2>}>, 'display-im6.q16.desktop': <{'position': <3>}>, 'gnome-language-selector.desktop': <{'position': <4>}>, 'libreoffice-startcenter.desktop': <{'position': <5>}>, 'libreoffice-calc.desktop': <{'position': <6>}>, 'libreoffice-draw.desktop': <{'position': <7>}>, 'libreoffice-impress.desktop': <{'position': <8>}>, 'libreoffice-math.desktop': <{'position': <9>}>, 'libreoffice-writer.desktop': <{'position': <10>}>, 'org.gnome.PowerStats.desktop': <{'position': <11>}>, 'org.remmina.Remmina.desktop': <{'position': <12>}>, 'org.gnome.Rhythmbox3.desktop': <{'position': <13>}>, 'org.gnome.Shotwell.desktop': <{'position': <14>}>, 'software-properties-gtk.desktop': <{'position': <15>}>, 'update-manager.desktop': <{'position': <16>}>, 'solaar.desktop': <{'position': <17>}>, 'gnome-session-properties.desktop': <{'position': <18>}>, 'usb-creator-gtk.desktop': <{'position': <19>}>, 'tableplus.desktop': <{'position': <20>}>, 'info.desktop': <{'position': <21>}>, 'org.gnome.TextEditor.desktop': <{'position': <22>}>, 'transmission-gtk.desktop': <{'position': <23>}>}, {'debian-uxterm.desktop': <{'position': <0>}>, 'vim.desktop': <{'position': <1>}>, 'virtualbox.desktop': <{'position': <2>}>, 'code.desktop': <{'position': <3>}>, 'debian-xterm.desktop': <{'position': <4>}>}]
disabled-extensions=@as []
enabled-extensions=['ding@rastersoft.com', 'ubuntu-dock@ubuntu.com', 'space-bar@luchrioh', 'just-perfection-desktop@just-perfection', 'tactile@lundal.io', 'switcher@landau.fi', 'tophat@fflewddur.github.io', 'tiling-assistant@ubuntu.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com']
favorite-apps=['vivaldi_vivaldi-stable.desktop', 'kitty.desktop']
last-selected-power-profile='power-saver'
welcome-dialog-last-shown-version='46.0'

[extensions/auto-move-windows]
application-list=['kitty.desktop:2', 'vivaldi_vivaldi-stable.desktop:1', 'steam_steam.desktop:3']

[extensions/dash-to-dock]
click-action='minimize-or-previews'
dash-max-icon-size=48
dock-fixed=false
dock-position='BOTTOM'
extend-height=false
hot-keys=false
multi-monitor=true
scroll-action='cycle-windows'
show-mounts=false
show-mounts-network=false
show-mounts-only-mounted=true

[extensions/ding]
check-x11wayland=true
show-home=false
start-corner='top-left'

[extensions/just-perfection]
accessibility-menu=true
animation=2
background-menu=true
clock-menu=true
clock-menu-position=0
controls-manager-spacing-size=0
dash=true
dash-icon-size=0
double-super-to-appgrid=true
events-button=true
max-displayed-search-results=0
osd=true
panel=true
panel-in-overview=true
panel-notification-icon=false
power-icon=true
quick-settings=true
quick-settings-dark-mode=true
ripple-box=true
search=true
show-apps-button=true
startup-status=0
support-notifier-showed-version=34
support-notifier-type=0
switcher-popup-delay=true
theme=false
top-panel-position=0
weather=false
window-demands-attention-focus=false
window-picker-icon=true
window-preview-caption=true
window-preview-close-button=true
workspace=true
workspace-background-corner-size=0
workspace-popup=true
workspaces-in-app-grid=true

[extensions/space-bar/appearance]
application-styles='.space-bar {\n  -natural-hpadding: 12px;\n}\n\n.space-bar-workspace-label.active {\n  margin: 0 2px;\n  background-color: rgba(255,255,255,0.3);\n  color: rgba(255,255,255,1);\n  border-color: rgba(0,0,0,0);\n  font-weight: 700;\n  border-radius: 4px;\n  border-width: 0px;\n  padding: 3px 8px;\n}\n\n.space-bar-workspace-label.inactive {\n  margin: 0 2px;\n  background-color: rgba(0,0,0,0);\n  color: rgba(255,255,255,1);\n  border-color: rgba(0,0,0,0);\n  font-weight: 700;\n  border-radius: 4px;\n  border-width: 0px;\n  padding: 3px 8px;\n}\n\n.space-bar-workspace-label.inactive.empty {\n  margin: 0 2px;\n  background-color: rgba(0,0,0,0);\n  color: rgba(255,255,255,0.5);\n  border-color: rgba(0,0,0,0);\n  font-weight: 700;\n  border-radius: 4px;\n  border-width: 0px;\n  padding: 3px 8px;\n}'
workspace-margin=2

[extensions/space-bar/behavior]
always-show-numbers=false
indicator-style='workspaces-bar'
position='left'
scroll-wheel='disabled'
show-empty-workspaces=true

[extensions/space-bar/shortcuts]
activate-empty-key=@as []
activate-previous-key=@as []
enable-move-to-workspace-shortcuts=true
move-workspace-left=@as []
move-workspace-right=@as []
open-menu=@as []

[extensions/space-bar/state]
version=34

[extensions/switcher]
font-size=uint32 24
icon-size=uint32 24
launcher-stats='{"gnome-keyboard-panel.desktop":3,"org.gnome.Settings.desktop":1,"kitty.desktop":18,"Alacritty.desktop":1,"gnome-display-panel.desktop":1,"org.gnome.Terminal.desktop":1,"org.gnome.Nautilus.desktop":1}'
max-width-percentage=uint32 70
show-switcher=['<Super>r']

[extensions/tactile]
background-color='rgba(128,247,255,0.1)'
border-color='rgba(128,237,255,0.5)'
col-2=1
col-3=1
row-2=0
text-color='rgb(25,141,196)'

[extensions/tiling-assistant]
active-window-hint-color='rgb(211,70,21)'
last-version-installed=46
overridden-settings={'org.gnome.mutter.edge-tiling': <@mb nothing>, 'org.gnome.mutter.keybindings.toggle-tiled-left': <@mb nothing>, 'org.gnome.mutter.keybindings.toggle-tiled-right': <@mb nothing>}
tiling-popup-all-workspace=true

[extensions/tophat]
cpu-display='chart'
mount-to-monitor='/'
show-fs=false

[keybindings]
screenshot=['<Shift><Super>p']
screenshot-window=['<Alt><Super>p']
show-screenshot-ui=['<Super>p']
switch-to-application-1=@as []
switch-to-application-2=@as []
switch-to-application-3=@as []
switch-to-application-4=@as []
toggle-message-tray=@as []
